# Generated by Django 5.2.7 on 2025-10-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='namee',
            new_name='name',
        ),
    ]
